name: "Render Pull Request Template"
description: "Replaces the placeholder in the pull request template with the actual repository name"
inputs:
  repo_name:
    description: "The name of the repository"
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Replace Placeholder in Pull Request Template
      run: |
        sed -i "s/\[REPO_NAME\]/${{ inputs.repo_name }}/g" .github/PULL_REQUEST_TEMPLATE.md

    - name: Commit changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add .github/PULL_REQUEST_TEMPLATE.md
        git commit -m "Render pull request template with repository name"
        git push origin ${{ github.head_ref }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
